id: A58B6A018
title: Rājagṛhanidāna
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:16:24.523857
  last_modified_at: 2022-03-01 22:16:24.523863
