id: A58B6A018
title: Why Koṭikarṇa was born with a golden ear-ring
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:16:24.541761
  last_modified_at: 2022-03-01 22:16:24.541764
