id: A58B6A018
title: Why Koṭikarṇa visits Hell
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:16:24.537072
  last_modified_at: 2022-03-01 22:16:24.537075
