id: A58B6A018
title: Koṭikarṇa, born with a golden ring in his ear, visits the Preta world
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:16:24.508485
  last_modified_at: 2022-03-01 22:16:24.508496
