id: A58B6A018
title: Carmavastūddāna
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:16:24.465290
  last_modified_at: 2022-03-01 22:16:24.465297
