id: A58B6A018
title: Śrāvastyānidāna
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:16:24.548324
  last_modified_at: 2022-03-01 22:16:24.548327
