id: A58B6A018
title: Vaiśālyānidāna
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:16:24.528672
  last_modified_at: 2022-03-01 22:16:24.528675
